const { SOCKET_EVENTS } = require('../../../constants');

const CLIENT_EVENTS = [
  SOCKET_EVENTS.SEND_MESSAGE,
  SOCKET_EVENTS.JOIN_BRAND_ROOM,
  SOCKET_EVENTS.USER_TYPING,
];

const SERVER_EVENTS = [
  SOCKET_EVENTS.RECEIVE_MESSAGE,
  SOCKET_EVENTS.BOT_TYPING,
  SOCKET_EVENTS.USER_TYPING,
  SOCKET_EVENTS.ERROR,
];

module.exports = { CLIENT_EVENTS, SERVER_EVENTS };
